vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix:     '%app.path.upload%'
    #        upload_destination: '%kernel.project_dir%/public/upload'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer