#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
    path: /home
    controller: App\Controller\HomeController::index

register_interest:
    path: /register-interest
    controller: 'App\Controller\UserEventsController::registerInterest'
    methods: [POST]
  