#index:
#    path: /
#    controller: App\Controller\DefaultController::index

Historique:
    path: /new
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\HistoriqueController::new